name: PHPStan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PHP version
        run: php -v

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run tests via PHPStan
        run: composer phpstan
